### ISSUE TITLE
Not getting latest sites with cloudflare ipfs

### ISSUE THREAD

**Issue by kcubeterm** [ipfs/dir-index-html#49] opened 2021-01-26 10:27 UTC
My latest sites show on ipfs with ipns but not with cloudflare getway.

Latest is https://ipfs.io/ipns/k51qzi5uqu5diddda9nm0f91pd9o2iaag71td786zosczje4kll4u9wmrwzbjf

Here cloudflare showing old sites. 
https://cloudflare-ipfs.com/ipns/k51qzi5uqu5diddda9nm0f91pd9o2iaag71td786zosczje4kll4u9wmrwzbjf

**Comment by jessicaschilling** [comment] 2021-01-26 18:16
This sounds like an issue with Cloudflare's gateway, not a bug in the directory index page code. Closing but feel free to open if this is not the case.

**Closed by jessicaschilling** 2021-01-26 18:16 UTC
Labels: need/triage

**Comment by kcubeterm** [comment] 2021-01-27 13:09
Now it's working. It took time. Thanks
